/**
 * QR Code Cryptographic Signing & Verification
 *
 * Uses HMAC-SHA256 (Web Crypto API) to sign QR payloads so customers
 * can only redeem stamps from QR codes generated by the admin panel.
 *
 * - Prevents QR fabrication (signature check)
 * - Prevents replay after timeout (expiry check)
 * - Prevents tampering (HMAC integrity)
 *
 * Set VITE_QR_SECRET in .env.local (shared by customer & business app).
 */

const QR_SECRET = (import.meta.env.VITE_QR_SECRET as string) || 'dev-fallback-not-for-production';
const QR_EXPIRY_MS = 5 * 60 * 1000; // 5 minutes

// ── Internal helpers ─────────────────────────────────────────────────────────

async function getKey(): Promise<CryptoKey> {
  const enc = new TextEncoder();
  return crypto.subtle.importKey(
    'raw',
    enc.encode(QR_SECRET),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
}

async function hmacHex(message: string): Promise<string> {
  const key = await getKey();
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return Array.from(new Uint8Array(sig))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

/** Constant-time-ish comparison (prevents timing side-channel in JS) */
function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Sign a QR payload with HMAC-SHA256 and add an expiry timestamp.
 * Returns a JSON string ready to encode in a QR code.
 *
 * @param payload  Data to include in the QR code
 * @param expiryMs Custom expiry (ms). Default 5 min. Use negative for tests.
 */
export async function signQrPayload(
  payload: Record<string, unknown>,
  expiryMs: number = QR_EXPIRY_MS,
): Promise<string> {
  const body = { ...payload, exp: Date.now() + expiryMs };
  const message = JSON.stringify(body);
  const sig = await hmacHex(message);
  return JSON.stringify({ ...body, sig });
}

/**
 * Verify a signed QR string. Checks HMAC integrity + expiry.
 * Returns the original payload (without `sig`) when valid.
 */
export async function verifyQrPayload(
  qrString: string,
): Promise<{ valid: boolean; payload?: Record<string, unknown>; error?: string }> {
  try {
    const data = JSON.parse(qrString);

    if (!data.sig || typeof data.sig !== 'string') {
      return { valid: false, error: 'QR code mist handtekening' };
    }

    // Fast-fail on expiry
    if (typeof data.exp === 'number' && Date.now() > data.exp) {
      return { valid: false, error: 'QR code is verlopen — vraag een nieuwe aan de kassa' };
    }

    // Verify HMAC
    const { sig, ...rest } = data;
    const message = JSON.stringify(rest);
    const expected = await hmacHex(message);

    if (!safeEqual(expected, sig)) {
      return { valid: false, error: 'QR code is ongeldig of vervalst' };
    }

    return { valid: true, payload: rest };
  } catch {
    return { valid: false, error: 'Ongeldige QR code' };
  }
}
